### ISSUE TITLE
nibabel problem 

### ISSUE THREAD

**Issue by MehriB** [Deep-MI/FastSurfer#34]
Hi,
I am trying to use FastFurfer segmentation only. but It seems in the very beginning it cannot import nibabel.
I use python version 3.6 and nibabel==2.5.1

when I run

(env) 0 [mbaniasadi2@iris-169 FastSurfer](2037687 1N/1T/8CN)$ bash run_fastsurfer.sh --fs_license license.txt --sid subject1 --sd /work/projects/ins_dbs/fastsurfer --t1 /work/projects/ins_dbs/fastsurfer/subject1/t1.nii.gz --seg_only

I get the following error:

/work/projects/ins_dbs/fastsurfer/FastSurfer/FastSurferCNN /work/projects/ins_dbs/fastsurfer/FastSurfer
python3.6 eval.py --in_name /work/projects/ins_dbs/fastsurfer/subject1/t1.nii.gz --out_name /work/projects/ins_dbs/fastsurfer/subject1/mri/aparc.DKTatlas+aseg.deep.mgz --order 1 --network_sagittal_path ../checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_axial_path ../checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_coronal_path ../checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --batch_size 8 --simple_run
Traceback (most recent call last):
  File "eval.py", line 19, in <module>
    import nibabel as nib
  File "/mnt/irisgpfs/projects/ins_dbs/fastsurfer/env/lib/python3.6/site-packages/nibabel/__init__.py", line 62, in <module>
    from . import analyze as ana
  File "/mnt/irisgpfs/projects/ins_dbs/fastsurfer/env/lib/python3.6/site-packages/nibabel/analyze.py", line 87, in <module>
    from .volumeutils import (native_code, swapped_code, make_dt_codes,
  File "/mnt/irisgpfs/projects/ins_dbs/fastsurfer/env/lib/python3.6/site-packages/nibabel/volumeutils.py", line 23, in <module>
    from .openers import Opener, BZ2File
  File "/mnt/irisgpfs/projects/ins_dbs/fastsurfer/env/lib/python3.6/site-packages/nibabel/openers.py", line 16, in <module>
    from bz2 import BZ2File
  File "/opt/apps/resif/data/production/v1.1-20180716/default/software/lang/Python/3.6.4-foss-2018a/lib/python3.6/bz2.py", line 23, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory

Thank you for the help,
Mehri

**Comment by LeHenschel** [comment]
Hey Mehri,

the messages states that the library libbz2.so.1.0 is missing on your machine. Looks like the bzip2 package is not installed. You can try installing it with:

`yum install bzip2-devel` for Centos or `sudo apt-get install libbz2-dev` for ubuntu/debian.

Best,
Leonie

**Comment by MehriB** [comment]
Thanks that was the problem. Now it is working. 

Bests,
Mehri
