### ISSUE TITLE
Numpy array error on docker image

### ISSUE THREAD

**Issue by AhmedFaisal95** [Deep-MI/FastSurfer#79]
## Bug Report

When running FastSurfer on the base docker image in the [current master version](https://github.com/Deep-MI/FastSurfer/tree/481add7d01682e05347d6d37fbc455e9a74653f9), I get a numpy error:
```
/fastsurfer/FastSurferCNN /fastsurfer
python3.6 eval.py --in_name /data/mri/T1.mgz --out_name /output/241395/mri/aparc.DKTatlas+aseg.deep.mgz --order 1 --network_sagittal_path /fastsurfer/checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_axial_path /fastsurfer/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_coronal_path /fastsurfer/checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --batch_size 2 --simple_run --run_viewagg_on check
Reading volume /data/mri/T1.mgz
Traceback (most recent call last):
  File "eval.py", line 462, in <module>
    fastsurfercnn(options.iname, options.oname, use_cuda, small_gpu, logger, options)
  File "eval.py", line 267, in fastsurfercnn
    header_info, affine_info, orig_data = load_and_conform_image(img_filename, interpol=1, logger=logger)
  File "/fastsurfer/FastSurferCNN/data_loader/load_neuroimaging_data.py", line 67, in load_and_conform_image
    orig = np.asanyarray(orig.dataobj, dtype=np.uint8)
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/_asarray.py", line 136, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
TypeError: __array__() takes 1 positional argument but 2 were given
```

## Steps to Reproduce

1. `git clone git@github.com:Deep-MI/FastSurfer.git`
2. `cd FastSurfer/`
3. `docker build --rm=true -t fastsurfer:tag_name -f ./Docker/Dockerfile .`
4. `docker run --gpus=all -v /path_to_data_dir/:/data -v /path_to_data_dir:/output --rm fastsurfer:tag_name --t1 /data/mri/T1.mgz --sd /output --sid 999 --seg_only --batch 2`

(Alternatively, I also tried using the `Dockerfile_FastSurferCNN` docker file)

3. `docker build --rm=true -t fastsurfer:tag_name -f ./Docker/Dockerfile_FastSurferCNN .`
4. `docker run --gpus=all -v /path_to_data_dir/:/data -v /path_to_data_dir:/output --rm fastsurfer:tag_name --in_name /data/mri/T1.mgz --out_name /path_to_data_dir/aparc.DKTatlas+aseg.deep.mgz --simple_run --batch 2`

## Expected Behavior

That the `eval.py` script runs and prints logs of the processing steps of Fastsurfer, as usual.

## Environment

* CPU: Intel® Xeon(R) CPU E5-2643 v3 @ 3.40GHz × 12
* OS: Ubuntu 20.04.3 LTS

## Additional Notes

...

**Comment by AhmedFaisal95** [comment]
This was fixed in https://github.com/Deep-MI/FastSurfer/commit/29fb8c1b19a24c08b2e6e199a814632d587dd554
