### ISSUE TITLE
RuntimeError:affine matrix has wrong number of rows

### ISSUE THREAD

**Issue by githubcooperation** [Deep-MI/FastSurfer#95]
Hey all,
I met following question when I using fastsurfer to process a subject. I want to know what should I do to solve this question.
(fastsurfe) [jichk@bme_login1 FastSurfer-master]$ ./run_fastsurfer.sh --t1 /hpc/data/home/bme/jichk/usr/DebugFastsurfer/001.mgz --sid 129028 --sd /hpc/data/home/bme/jichk/usr/DebugFastsurfer --parallel --threads 4
Fri Dec 24 17:52:13 CST 2021

~/FastSurfer-master/FastSurferCNN ~/FastSurfer-master
python3.6 eval.py --in_name /hpc/data/home/bme/jichk/usr/DebugFastsurfer/001.mgz --out_name /hpc/data/home/bme/jichk/usr/DebugFastsurfer/129028/mri/aparc.DKTatlas+aseg.deep.mgz --order 1 --network_sagittal_path /hpc/data/home/bme/jichk/FastSurfer-master/checkpoints/Sagittal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_axial_path /hpc/data/home/bme/jichk/FastSurfer-master/checkpoints/Axial_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --network_coronal_path /hpc/data/home/bme/jichk/FastSurfer-master/checkpoints/Coronal_Weights_FastSurferCNN/ckpts/Epoch_30_training_state.pkl --batch_size 8 --simple_run --run_viewagg_on check
Reading volume /hpc/data/home/bme/jichk/usr/DebugFastsurfer/001.mgz
Conforming image to UCHAR, RAS orientation, and 1mm isotropic voxels
Input:    min: 0.0  max: 3433.571533203125
rescale:  min: 0.0  max: 1411.1979001464842  scale: 0.1806975477879684
Traceback (most recent call last):
  File "eval.py", line 462, in <module>
    fastsurfercnn(options.iname, options.oname, use_cuda, small_gpu, logger, options)
  File "eval.py", line 267, in fastsurfercnn
    header_info, affine_info, orig_data = load_and_conform_image(img_filename, interpol=1, logger=logger)
  File "/hpc/data/home/bme/jichk/FastSurfer-master/FastSurferCNN/data_loader/load_neuroimaging_data.py", line 62, in load_and_conform_image
    orig = conform(orig, interpol)
  File "/hpc/data/home/bme/jichk/FastSurfer-master/FastSurferCNN/data_loader/conform.py", line 229, in conform
    mapped_data = map_image(img, h1.get_affine(), h1.get_data_shape(), order=order)
  File "/hpc/data/home/bme/jichk/FastSurfer-master/FastSurferCNN/data_loader/conform.py", line 85, in map_image
    new_data = affine_transform(img.get_data(), inv(vox2vox), output_shape=out_shape, order=order)
  File "/hpc/data/home/bme/jichk/anaconda3/envs/fastsurfe/lib/python3.6/site-packages/scipy/ndimage/interpolation.py", line 449, in affine_transform
    raise RuntimeError('affine matrix has wrong number of rows')
RuntimeError: affine matrix has wrong number of rows
Best,
Maylin

**Comment by LeHenschel** [comment]
Hey Maylin,

it looks like the affine matrix associated with the image you are trying to process might have multiple input frames. Can you post the header information for the image in question? 

Best,
Leonie

**Comment by githubcooperation** [comment]
Hey Leonie,
Thanks for you can solve my question first. The header information is in the following figure:
![bug](https://user-images.githubusercontent.com/48356035/148535095-9683a3f6-9975-4c6f-8a9d-af9b162c69ff.png)
Best,
Maylin

**Comment by LeHenschel** [comment]
Hey, the screenshot does not show the affine matrix. It would be helpful to see the full header information and the full affine information (either the output of mri_info or if you are using nibabel 
```python
img = nib.load("yourimage.nii.gz")
print(img.header)
print(img.affine)
```

**Comment by m-reuter** [comment]
closing due to inactivity
